### ISSUE TITLE
Server returns 500 (Internal Server Error)

### ISSUE THREAD

**Issue by fynngodau** [pajowu/db-python#2]
While trying to figure out how to use this library, it was not working. This was because the `BahnAPI` `searchLocation` function is receiving HTTP status code `500` from the server.

**Comment by h110m** [comment]
Which Version of python are you using?
It looks like the crypto module doesn't work properly try replacing the key (line 19 in Bahn.py) with following string:
`"aH6F8zRuiBnm33fU"`

**Comment by pajowu** [comment]
Please try using https://github.com/FahrplanDatenGarten/pyhafas instead
